# Generated by Django 5.2.7 on 2025-10-25 18:57

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_hora', models.DateTimeField()),
                ('lugar', models.CharField(max_length=200)),
                ('imagen_url', models.CharField(default='img/default_event.jpg', max_length=500)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cupo_total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(default=datetime.datetime.now)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Registros',
                'unique_together': {('usuario', 'evento')},
            },
        ),
    ]
