# Generated by Django 5.2.7 on 2025-10-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_registro_fecha_registro_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
